services:
  - name: kuchitee-server
    type: web
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: CLIENT_URL
        value: https://kuchitee.vercel.app