export interface Product {
  id: string;
  niche: string;
  name: string;
  title: string;
  description: string;
  longDescription: string;
  price: number;
  image: string;
  color: string;
  sizes: string[];
  colors: string[];
  tags: string[];
  inStock: boolean;
}

export const PRODUCTS: Product[] = [
  // ANIME - DRAGON BALL (4)
  {
    id: 'goku-spirit',
    niche: 'anime',
    name: 'GOKU SPIRIT',
    title: 'Goku Spirit - Dragon Ball Legend',
    description: 'Premium streetwear celebrating the legendary Goku spirit. Dynamic action pose with golden aura.',
    longDescription: 'Experience the legendary power of the Saiyan warrior with our Goku Spirit tee. This premium oversized streetwear features a dynamic action pose with golden aura effects that capture the iconic Super Saiyan transformation. Made from 100% premium cotton with a dropped shoulder fit for that authentic streetwear aesthetic.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DRAGONBALL_001-Q5fK7TCViFhWDMBsbmA2Zv.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'dragonball', 'goku'],
    inStock: true,
  },
  {
    id: 'super-saiyan-vibes',
    niche: 'anime',
    name: 'SUPER SAIYAN VIBES',
    title: 'Super Saiyan Vibes - Transformation',
    description: 'Transformation design with electric effects and Super Saiyan energy.',
    longDescription: 'Channel the power of transformation with our Super Saiyan Vibes tee. Featuring electric effects and radiating energy lines, this design captures the intensity of the legendary Super Saiyan transformation.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DRAGONBALL_002-Q5fK7TCViFhWDMBsbmA2Zv.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'dragonball', 'saiyan'],
    inStock: true,
  },
  {
    id: 'dragon-ball-legacy',
    niche: 'anime',
    name: 'DRAGON BALL LEGACY',
    title: 'Dragon Ball Legacy - Iconic Design',
    description: 'Iconic dragon ball with retro anime style. Celebrate the legacy of anime.',
    longDescription: 'Celebrate the legacy of anime with our Dragon Ball Legacy tee. This iconic design features the legendary dragon ball with a retro anime aesthetic that pays homage to the series that started it all.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DRAGONBALL_003-Q5fK7TCViFhWDMBsbmA2Zv.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'dragonball', 'legacy'],
    inStock: true,
  },
  {
    id: 'kamehameha',
    niche: 'anime',
    name: 'KAMEHAMEHA',
    title: 'Kamehameha - Energy Blast',
    description: 'Energy blast design with bold typography. The most iconic attack.',
    longDescription: 'Unleash the most iconic attack in anime history with our Kamehameha tee. Bold typography combined with a powerful energy blast design makes this tee a must-have for any anime fan.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DRAGONBALL_005-Q5fK7TCViFhWDMBsbmA2Zv.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'dragonball', 'attack'],
    inStock: true,
  },
  // ANIME - DEMON SLAYER (4)
  {
    id: 'tanjiro-warrior',
    niche: 'anime',
    name: 'TANJIRO WARRIOR',
    title: 'Tanjiro Warrior - Demon Slayer',
    description: 'Tanjiro in combat stance with demon slayer sword. Dark anime aesthetic.',
    longDescription: 'Join the Demon Slayer Corps with our Tanjiro Warrior tee. Featuring Tanjiro in combat stance with his signature nichirin sword, this design captures the dark and intense aesthetic of the series.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DEMONSLAYER_001-2NjDU4HgBrCZTQJtgCYFMS.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'demonslayer', 'tanjiro'],
    inStock: true,
  },
  {
    id: 'demon-slayer-corps',
    niche: 'anime',
    name: 'DEMON SLAYER CORPS',
    title: 'Demon Slayer Corps - Organization',
    description: 'Iconic demon slayer logo with Japanese elements.',
    longDescription: 'Rep the Demon Slayer Corps with our official Corps tee. Featuring the iconic logo with traditional Japanese elements, this tee represents the brave warriors who protect humanity from demons.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DEMONSLAYER_002-djtucdghUwrsRNoMhPiNP2.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'demonslayer', 'corps'],
    inStock: true,
  },
  {
    id: 'breathing-technique',
    niche: 'anime',
    name: 'BREATHING TECHNIQUE',
    title: 'Breathing Technique - Water Breathing',
    description: 'Artistic representation of water breathing with fluid design.',
    longDescription: 'Master the breathing techniques with our Water Breathing tee. Artistic fluid designs represent the elegant and deadly combat style used by the Demon Slayer Corps.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DEMONSLAYER_003-CTQAm6z4k4SJRZcvbzaSU4.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'demonslayer', 'breathing'],
    inStock: true,
  },
  {
    id: 'hashira-power',
    niche: 'anime',
    name: 'HASHIRA POWER',
    title: 'Hashira Power - Elite Warriors',
    description: 'Demon slayer hashira character design with warrior aesthetic.',
    longDescription: 'Honor the elite warriors of the Demon Slayer Corps with our Hashira Power tee. This design features the powerful hashira in their full warrior glory, representing the pinnacle of demon slaying strength.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_DEMONSLAYER_004-j2AmozP8E5mGAdVwAKVexc.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'demonslayer', 'hashira'],
    inStock: true,
  },
  // ANIME - NARUTO (4)
  {
    id: 'naruto-ninja',
    niche: 'anime',
    name: 'NARUTO NINJA',
    title: 'Naruto Ninja - Shinobi Spirit',
    description: 'Naruto in ninja pose with kunai. Dynamic action design.',
    longDescription: 'Embrace the Shinobi spirit with our Naruto Ninja tee. Featuring Naruto in dynamic action pose with kunai, this design captures the energy and determination of the hidden leaf villages most famous ninja.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_NARUTO_001-gJb3DdVTB67Q3CfqMcy6rC.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'naruto', 'ninja'],
    inStock: true,
  },
  {
    id: 'sharingan-power',
    niche: 'anime',
    name: 'SHARINGAN POWER',
    title: 'Sharingan Power - Eye of the Uchiha',
    description: 'Iconic Sharingan eye design with red and black colors.',
    longDescription: 'Unlock the power of the Sharingan with our Eye of the Uchiha tee. The iconic tomoe design in striking red and black represents the legendary dojutsu of the Uchiha clan.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_NARUTO_002-5Hk8LJC2AF4poTtLoAUCxx.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'naruto', 'sharingan'],
    inStock: true,
  },
  {
    id: 'hidden-leaf-village',
    niche: 'anime',
    name: 'HIDDEN LEAF VILLAGE',
    title: 'Hidden Leaf Village - Konoha Pride',
    description: 'Naruto village symbol with ninja culture.',
    longDescription: 'Rep the Hidden Leaf Village with our Konoha Pride tee. Featuring the iconic village symbol, this tee celebrates the ninja culture and community that shaped Naruto into the hero he became.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_NARUTO_003-bXUA7TPBWxr9CHDdQ77qMe.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'naruto', 'village'],
    inStock: true,
  },
  {
    id: 'chakra-energy',
    niche: 'anime',
    name: 'CHAKRA ENERGY',
    title: 'Chakra Energy - Spiritual Power',
    description: 'Chakra visualization design with spiritual elements.',
    longDescription: 'Tap into your spiritual energy with our Chakra Energy tee. This design visualizes the life force energy that powers all ninja techniques, with intricate spiritual elements.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_NARUTO_004-hiGUw3iCdfteJ9etEaFJRW.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'naruto', 'chakra'],
    inStock: true,
  },
  // ANIME - MODERN MIX (4)
  {
    id: 'jujutsu-kaisen',
    niche: 'anime',
    name: 'JUJUTSU KAISEN',
    title: 'Jujutsu Kaisen - Cursed Energy',
    description: 'Yuji Itadori with cursed energy design.',
    longDescription: 'Dive into the world of Jujutsu with our Cursed Energy tee. Featuring Yuji Itadori surrounded by cursed energy, this design captures the dark and action-packed essence of Jujutsu Kaisen.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_MODERN_001-6xZM5hyrpBxGvm3nLHrxqB.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'jujutsu', 'kaisen'],
    inStock: true,
  },
  {
    id: 'my-hero-academia',
    niche: 'anime',
    name: 'MY HERO ACADEMIA',
    title: 'My Hero Academia - Hero Culture',
    description: 'All Might iconic pose with hero culture.',
    longDescription: 'Go beyond with our Hero Culture tee. Featuring All Might in his iconic pose, this design celebrates the spirit of heroism and the journey to becoming the greatest hero.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_MODERN_002-dMSRCavgyPxTFEARCfVUMt.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'mha', 'hero'],
    inStock: true,
  },
  {
    id: 'one-piece-adventure',
    niche: 'anime',
    name: 'ONE PIECE ADVENTURE',
    title: 'One Piece Adventure - Pirate King',
    description: 'Luffy pirate design with adventure aesthetic.',
    longDescription: 'Set sail for adventure with our Pirate King tee. Featuring Luffy in his pirate glory, this design embodies the spirit of freedom and the endless pursuit of dreams.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_MODERN_003-R2cX5CfvwYqU6nhW8xpWsC.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'onepiece', 'adventure'],
    inStock: true,
  },
  {
    id: 'attack-on-titan',
    niche: 'anime',
    name: 'ATTACK ON TITAN',
    title: 'Attack on Titan - Titan Slayer',
    description: 'Titan slayer design with action-packed imagery.',
    longDescription: 'Join the fight against the Titans with our Titan Slayer tee. Action-packed imagery captures the intensity and desperation of humanity last stand against the giant Titans.',
    price: 22.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/ANIME_MODERN_004-RM8TkjnAfYJEEG7oWTRFf3.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['anime', 'aot', 'titan'],
    inStock: true,
  },
  // GAMING - LIFESTYLE (5)
  {
    id: 'pro-gamer',
    niche: 'gaming',
    name: 'PRO GAMER',
    title: 'Pro Gamer - Esports Legacy',
    description: 'Esports player in action with gaming setup. Neon colors.',
    longDescription: 'Level up your style with our Pro Gamer tee. Featuring an esports player in action with gaming setup, neon accents capture the electric energy of competitive gaming.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_ESPORTS_001-U3Wb8koKyFBMefPeMCW4x3.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'esports', 'pro'],
    inStock: true,
  },
  {
    id: 'level-up',
    niche: 'gaming',
    name: 'LEVEL UP',
    title: 'Level Up - Progression',
    description: 'Retro gaming design with pixel art and modern streetwear.',
    longDescription: 'Every legend was once a beginner. Our Level Up tee combines retro pixel art aesthetics with modern streetwear sensibilities, celebrating the gaming journey.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_ESPORTS_002-YqbYVmNQeapoGMWHJ4gmKT.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'retro', 'levelup'],
    inStock: true,
  },
  {
    id: 'clutch-play',
    niche: 'gaming',
    name: 'CLUTCH PLAY',
    title: 'Clutch Play - Competitive Moment',
    description: 'Esports competitive gaming moment design.',
    longDescription: 'The clutch moment that defines legends. Our Clutch Play tee captures that heart-pounding competitive gaming moment when everything is on the line.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_ESPORTS_003-4TiTHdk2DpXPnaYTSFxdqK.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'clutch', 'competitive'],
    inStock: true,
  },
  {
    id: 'gamer-mindset',
    niche: 'gaming',
    name: 'GAMER MINDSET',
    title: 'Gamer Mindset - Mental Game',
    description: 'Motivational gaming design with controller elements.',
    longDescription: 'Gaming is 10% mechanics and 90% mindset. Our Gamer Mindset tee combines motivational elements with controller aesthetics for the ultimate gaming culture streetwear.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_ESPORTS_004-dpttjtdseoUgVAtGwNeRLD.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'mindset', 'motivation'],
    inStock: true,
  },
  {
    id: 'respawn',
    niche: 'gaming',
    name: 'RESPAWN',
    title: 'Respawn - Second Chance',
    description: 'Gaming culture design with phoenix/respawn theme.',
    longDescription: 'Rise again. Our Respawn tee features the iconic phoenix/respawn theme that represents the gaming culture of never giving up and always coming back stronger.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_ESPORTS_005-UD4Koca9eqvyGJ8nNJES6R.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'respawn', 'phoenix'],
    inStock: true,
  },
  // GAMING - TITLES (5)
  {
    id: 'call-of-duty',
    niche: 'gaming',
    name: 'CALL OF DUTY',
    title: 'Call of Duty - Tactical Ops',
    description: 'Soldier in action with tactical gear.',
    longDescription: 'Deploy in style with our Tactical Ops tee. Featuring a soldier in action with full tactical gear, this design captures the intensity of modern military shooters.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_TITLES_001-CgnjfGxecQVKRvZ9HFCjsB.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'cod', 'fps'],
    inStock: true,
  },
  {
    id: 'valorant-agent',
    niche: 'gaming',
    name: 'VALORANT AGENT',
    title: 'Valorant Agent - Tactical Shooter',
    description: 'Valorant character with tactical design.',
    longDescription: 'Choose your agent. Our Valorant Agent tee features tactical design elements that capture the strategic depth and unique character identities of the game.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_TITLES_002-6FZaWvFurNazPe4ZxQLBce.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'valorant', 'tactical'],
    inStock: true,
  },
  {
    id: 'fortnite-battle',
    niche: 'gaming',
    name: 'FORTNITE BATTLE',
    title: 'Fortnite Battle - Battle Royale',
    description: 'Battle royale gaming design with action elements.',
    longDescription: 'Victory Royale awaits. Our Fortnite Battle tee captures the explosive energy of the battle royale genre with action-packed design elements.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_TITLES_003-EiSkTSUwrKR3FSEC6yNaL5.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'fortnite', 'br'],
    inStock: true,
  },
  {
    id: 'pubg-survivor',
    niche: 'gaming',
    name: 'PUBG SURVIVOR',
    title: 'PUBG Survivor - Survival Game',
    description: 'Survival game design with parachute elements.',
    longDescription: 'Drop in, gear up, survive. Our PUBG Survivor tee features parachute elements and survival aesthetics that capture the tension of the battle royale genre.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_TITLES_004-SHzQ4NshHwEJxQ4jYMJXUq.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'pubg', 'survival'],
    inStock: true,
  },
  {
    id: 'minecraft-builder',
    niche: 'gaming',
    name: 'MINECRAFT BUILDER',
    title: 'Minecraft Builder - Creative Mode',
    description: 'Blocky pixel art design with creative gaming culture.',
    longDescription: 'In a world of blocks, your imagination is the limit. Our Minecraft Builder tee features authentic pixel art that celebrates the creative gaming culture.',
    price: 21.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/GAMING_TITLES_005-gDUjUuTyfmcN3CK3Vtcaif.png',
    color: 'Black',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['gaming', 'minecraft', 'builder'],
    inStock: true,
  },
  // FOOTBALL (10)
  {
    id: 'cr7-forever',
    niche: 'football',
    name: 'CR7 FOREVER',
    title: 'CR7 Forever - Cristiano Ronaldo Tribute',
    description: "Premium football streetwear celebrating the GOAT. Features iconic CR7 imagery.",
    longDescription: 'The GOAT deserves GOAT-level tribute. Our CR7 Forever tee features iconic imagery celebrating Cristiano Ronaldos legendary career and unmatched dedication to the beautiful game.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_001_CR7_LEGEND-G9WTgaEk8vEFCgcT75ysnQ.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'cr7', 'ronaldo'],
    inStock: true,
  },
  {
    id: 'messi-magic',
    niche: 'football',
    name: 'MESSI MAGIC',
    title: 'Messi Magic - Lionel Messi Tribute',
    description: "Celebrate football excellence with Messi's dribbling artistry.",
    longDescription: 'Artistry on the pitch. Our Messi Magic tee celebrates the dribbling genius of Lionel Messi and his magical ability to create moments of pure football beauty.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_002_MESSI_MAGIC-n7uUhYPpQiGEuwtywW2MpD.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'messi', 'soccer'],
    inStock: true,
  },
  {
    id: 'saudi-pro-league',
    niche: 'football',
    name: 'SAUDI PRO LEAGUE',
    title: 'Saudi Pro League - Local Pride',
    description: 'Show your pride for Saudi Pro League football.',
    longDescription: 'The new frontier of football. Our Saudi Pro League tee celebrates the rapid growth and exciting stars of the Saudi football revolution.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_003_SAUDI_PRO_LEAGUE-j9VZkT3PwCRxKQ9Nc9A3NV.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'saudi', 'league'],
    inStock: true,
  },
  {
    id: 'goat-culture',
    niche: 'football',
    name: 'GOAT CULTURE',
    title: 'GOAT Culture - Greatest of All Time',
    description: 'Celebrate football excellence with this GOAT culture design.',
    longDescription: 'Greatest of All Time. Our GOAT Culture tee celebrates football excellence and the legendary players who have transcended the sport.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_004_GOAT_CULTURE-gzAf2s2VbQNGCVmxRqF8Gr.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'goat', 'culture'],
    inStock: true,
  },
  {
    id: 'passion-game',
    niche: 'football',
    name: 'PASSION GAME',
    title: 'Passion Game - Football Love',
    description: 'For those who live and breathe football.',
    longDescription: 'Football is life. Our Passion Game tee is for those who live and breathe the beautiful game, 24/7, 365 days a year.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_005_PASSION_GAME-az2NnpaVWWp2p2TVF4TgcK.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'passion', 'game'],
    inStock: true,
  },
  {
    id: 'neymar-magic',
    niche: 'football',
    name: 'NEYMAR MAGIC',
    title: 'Neymar Magic - Flair & Skill',
    description: 'Neymar-inspired design with dribbling artistry and flair.',
    longDescription: 'Joga Bonito. Our Neymar Magic tee celebrates the dribbling artistry and flair that has made Neymar one of the most exciting players in football history.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_006_NEYMAR_MAGIC-JDHqANJwgzcyAWdSwyo8Vr.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'neymar', 'magic'],
    inStock: true,
  },
  {
    id: 'haaland-striker',
    niche: 'football',
    name: 'HAALAND STRIKER',
    title: 'Haaland Striker - Goal Machine',
    description: 'Erling Haaland goal celebration design with power.',
    longDescription: 'Machine. Our Haaland Striker tee captures the unstoppable goal-scoring power of Erling Haaland and his incredible ability to find the back of the net.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_007_HAALAND_STRIKER-KdRUVmd6KMABU4txv6ktde.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'haaland', 'striker'],
    inStock: true,
  },
  {
    id: 'benzema-legend',
    niche: 'football',
    name: 'BENZEMA LEGEND',
    title: 'Benzema Legend - Football Artistry',
    description: 'Karim Benzema elegance and football artistry.',
    longDescription: 'The French King. Our Benzema Legend tee celebrates the elegant football artistry of Karim Benzema and his journey from prodigy to Ballon dOr winner.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_008_BENZEMA_LEGEND-85kqBCjAWLsWAnLYcZgova.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'benzema', 'legend'],
    inStock: true,
  },
  {
    id: 'football-united',
    niche: 'football',
    name: 'FOOTBALL UNITED',
    title: 'Football United - Diversity & Teamwork',
    description: 'Diverse players united in football passion.',
    longDescription: 'Football unites. Our Football United tee celebrates the diversity and teamwork that makes football the worlds beautiful game.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_009_FOOTBALL_UNITED-PoFAYu49xXTVfkCrLNMxPQ.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'unity', 'teamwork'],
    inStock: true,
  },
  {
    id: 'champions-mindset',
    niche: 'football',
    name: 'CHAMPIONS MINDSET',
    title: 'Champions Mindset - Trophy Culture',
    description: 'Trophy and winner imagery celebrating championship culture.',
    longDescription: 'Winners mentality. Our Champions Mindset tee celebrates the trophy culture and winning attitude that separates champions from the rest.',
    price: 24.99,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310419663032253817/W9dXJiEivXdpfNxcR8cgna/FOOTBALL_BATCH1_010_CHAMPIONS_MINDSET-5G2W2wLWitWjL9q247suHt.png',
    color: 'Black',
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    tags: ['football', 'champions', 'mindset'],
    inStock: true,
  },
];

export const NICHES = [
  {
    id: 'anime',
    name: 'Anime',
    icon: '🎌',
    color: 'from-purple-600',
    description: 'Anime and manga inspired designs',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    icon: '🎮',
    color: 'from-cyan-600',
    description: 'Gaming culture and esports passion',
  },
  {
    id: 'football',
    name: 'Football',
    icon: '⚽',
    color: 'from-red-600',
    description: 'Premium football streetwear',
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByNiche(niche: string): Product[] {
  return PRODUCTS.filter((p) => p.niche === niche);
}

export function getNicheInfo(nicheId: string) {
  return NICHES.find((n) => n.id === nicheId);
}
